services:
#AxonServer     
  axon:
   container_name: axon
   image: axoniq/axonserver:2024.2.0
   environment:
     - AXONIQ_AXONSERVER_DEVMODE_ENABLED=true
     - AXONIQ_AXONSERVER_STANDALONE=true
   ports:
     - "8024:8024"
     - "8124:8124"
#Cassandra
  cassandra:
   container_name: cassandra
   image: cassandra:latest
   ports:
     - "9042:9042"
   
